In [170]:
import pandas as pd
import numpy as np
from keras.layers import Dense,Dropout,Embedding,GlobalAveragePooling1D
from keras.optimizers import SGD,Adam
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [72]:
train_set = pd.read_csv('train.csv')

In [73]:
test_set = pd.read_csv('test.csv')

In [119]:
train_check = pd.DataFrame({'A':train_set['effectiveness_rating'],'B':train_set['number_of_times_prescribed']})

In [166]:
train_set.head()

patient_id   name_of_drug        use_case_for_drug  \
0       46914        Xenical                  Obesity   
1       36858       Fentanyl                     Pain   
2       14167  Triamcinolone                 Neuritis   
3      223266      Estradiol  Postmenopausal Symptoms   
4      188914       Arimidex             Breast Cance   

                                   review_by_patient  effectiveness_rating  \
0  "Xenical really helped me, but some of the bow...                     7   
1  "I don&#039;t think I could make it without th...                    10   
2         "this drug worked for me but is very slow"                     7   
3  "I was very reluctant to use this method, but ...                     8   
4  "Debilitating joint and bone pain forced me of...                     2   

   drug_approved_by_UIC  number_of_times_prescribed  base_score  \
0               39502.0                          50    2.386411   
1               39502.0                          22    8.757201   
2               39502.0                           2    5.771317   
3               39502.0                          43    5.665839   
4               39502.0                         292    8.306315   

           review  check  Passed  
0  (0.898, 6.788]      0     0.0  
1  (6.788, 8.992]      1     NaN  
2  (0.898, 6.788]      0     NaN  
3  (0.898, 6.788]      0     NaN  
4  (6.788, 8.992]      1     NaN

In [164]:
for dataset in df:
    dataset['check']=1
    dataset.loc[dataset['base_score']<6.5,'check']=0

In [174]:
token = Tokenizer(oov_token= '<OOV>')
sentences = train_set['review_by_patient']
token.fit_on_texts(sentences)
sequences = token.texts_to_sequences(sentences)
padded = pad_sequences(sequences,padding = 'post',maxlen = 300,truncating = 'post')

In [179]:
y = train_set['check']
vocab_size = len(token.word_index)
model_seq = Sequential([
    Embedding(vocab_size,64,input_length = 300),
    GlobalAveragePooling1D(),
    Dense(6,activation = 'relu'),
    Dense(1,activation = 'sigmoid')
])
model_seq.compile(loss='binary_crossentropy',optimizer='adam',metrics = ['accuracy'])
model_seq.fit(padded[0:20000],y[0:20000],epochs = 5)
C = model.predict(padded[0:20000])

Epoch 1/5
20000/20000 [==============================] - 27s 1ms/step - loss: 0.6737 - accuracy: 0.6037
Epoch 2/5
20000/20000 [==============================] - 27s 1ms/step - loss: 0.6701 - accuracy: 0.6037
Epoch 3/5
20000/20000 [==============================] - 28s 1ms/step - loss: 0.6677 - accuracy: 0.6037
Epoch 4/5
20000/20000 [==============================] - 28s 1ms/step - loss: 0.6621 - accuracy: 0.6037
Epoch 5/5
20000/20000 [==============================] - 28s 1ms/step - loss: 0.6409 - accuracy: 0.6252


ValueError: Number of features of the model must match the input. Model n_features is 2 and input n_features is 300 

In [185]:
C = model_seq.predict(padded[0:20000])
C[0:200]

array([[0.64253575],
       [0.71424127],
       [0.55714506],
       [0.6102717 ],
       [0.5942905 ],
       [0.6473215 ],
       [0.60991883],
       [0.5914458 ],
       [0.60991883],
       [0.5909014 ],
       [0.58229226],
       [0.69603515],
       [0.58229226],
       [0.7719898 ],
       [0.55557686],
       [0.5826365 ],
       [0.620599  ],
       [0.56975645],
       [0.6774952 ],
       [0.6236308 ],
       [0.7678734 ],
       [0.56049025],
       [0.6469048 ],
       [0.53188527],
       [0.68790424],
       [0.6469048 ],
       [0.68790424],
       [0.57772523],
       [0.7012974 ],
       [0.6717653 ],
       [0.7864534 ],
       [0.58441997],
       [0.7694248 ],
       [0.6608541 ],
       [0.69233376],
       [0.2568503 ],
       [0.6471837 ],
       [0.56753135],
       [0.6774647 ],
       [0.6683309 ],
       [0.5441575 ],
       [0.6683309 ],
       [0.70893335],
       [0.7521776 ],
       [0.6428579 ],
       [0.6737957 ],
       [0.6006544 ],
       [0.600

In [134]:
model = RandomForestRegressor()

In [135]:
model.fit(train_check,y_check)

C:\Users\SHALIN\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [99]:
model.predict(train_check[0:10])

array([2.7276718 , 8.75720099, 5.77131687, 5.66583897, 8.24608897,
       7.65760612, 8.56327449, 7.34645317, 8.56327449, 7.92792564])

In [88]:
y_check[0:10]

0    2.386411
1    8.757201
2    5.771317
3    5.665839
4    8.306315
5    7.760232
6    8.563274
7    7.346453
8    8.563274
9    7.927926
Name: base_score, dtype: float64

In [100]:
test_set.head()

patient_id name_of_drug                                  review_by_patient  \
0      163740  Mirtazapine  "I&#039;ve tried a few antidepressants over th...   
1       39293     Contrave  "Contrave combines drugs that were used for al...   
2      208087      Zyclara  "4 days in on first 2 weeks.  Using on arms an...   
3       23295    Methadone  "Ive been on Methadone for over ten years and ...   
4       97013       Ambien  "Ditto on rebound sleepless when discontinued....   

   drug_approved_by_UIC  number_of_times_prescribed  use_case_for_drug  \
0               40967.0                          22         Depression   
1               42799.0                          35        Weight Loss   
2               41823.0                          13          Keratosis   
3               42661.0                          21  Opiate Withdrawal   
4               42017.0                          44           Insomnia   

   effectiveness_rating  
0                    10  
1                     9  
2                     4  
3                     7  
4                     2

In [123]:
test_check = pd.DataFrame({'A':test_set['effectiveness_rating'],'B':test_set['number_of_times_prescribed']})

In [102]:
test_check.head()

A   B        C
0  10  22  40967.0
1   9  35  42799.0
2   4  13  41823.0
3   7  21  42661.0
4   2  44  42017.0

In [103]:
Predictions = model.predict(test_check)

In [107]:
Predictions[0:5]

array([8.75720099, 8.74503683, 5.95227784, 5.99490436, 6.13368021])

In [105]:
submissions = pd.DataFrame({'patient_id':test_set['patient_id'],'base_score':Predictions})

In [106]:
submissions.head()

patient_id  base_score
0      163740    8.757201
1       39293    8.745037
2      208087    5.952278
3       23295    5.994904
4       97013    6.133680

In [29]:
submissions.to_csv('submission1.csv',index = False)

In [129]:
from sklearn.ensemble import ExtraTreesRegressor

In [130]:
model2 = ExtraTreesRegressor()

In [131]:
model2.fit(train_check,y_check)

C:\Users\SHALIN\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_decrease=0.0, min_impurity_split=None,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
          oob_score=False, random_state=None, verbose=0, warm_start=False)

In [132]:
model2.score(train_check,y_check)

1.0

In [136]:
model.score(train_check,y_check)

0.9989148856363997

In [112]:
Predictions2 = model2.predict(test_check)

In [113]:
submissions2 = pd.DataFrame({'patient_id':test_set['patient_id'],'base_score':Predictions2})

In [114]:
submissions2.to_csv('submission3.csv',index = False)

In [115]:
Predictions2[0:10]

array([8.75720099, 7.37567133, 5.96297031, 5.36429696, 6.9396052 ,
       7.69617343, 8.35895072, 6.12747517, 2.23483994, 6.6235953 ])

In [116]:
Predictions[0:10]

array([8.75720099, 8.74503683, 5.95227784, 5.99490436, 6.13368021,
       7.47509663, 8.35895072, 6.12747517, 2.23483994, 6.48599413])

In [69]:
model_go = Sequential([
    Dense(500, input_dim=2, activation= "relu"),
    Dense(200, activation= "relu"),
    Dense(75, activation= "relu"),
    Dense(25, activation= "relu"),
    Dense(1)
])

In [70]:
model_go.compile(loss='mean_squared_error',optimizer = "adam",metrics=['accuracy'])

In [71]:
history = model_go.fit(train_check,y_check,epochs = 300,verbose=1)

Epoch 1/300
32165/32165 [==============================] - 3s 82us/step - loss: 3.0318 - accuracy: 0.0000e+00
Epoch 2/300
32165/32165 [==============================] - 2s 71us/step - loss: 1.3754 - accuracy: 0.0000e+00
Epoch 3/300
32165/32165 [==============================] - 2s 71us/step - loss: 1.3366 - accuracy: 0.0000e+00
Epoch 4/300
32165/32165 [==============================] - 2s 76us/step - loss: 1.1892 - accuracy: 0.0000e+00
Epoch 5/300
32165/32165 [==============================] - 2s 73us/step - loss: 1.0713 - accuracy: 0.0000e+00
Epoch 6/300
32165/32165 [==============================] - 2s 74us/step - loss: 0.9884 - accuracy: 0.0000e+00
Epoch 7/300
32165/32165 [==============================] - 3s 79us/step - loss: 0.9408 - accuracy: 0.0000e+00
Epoch 8/300
32165/32165 [==============================] - 3s 86us/step - loss: 0.8989 - accuracy: 0.0000e+00
Epoch 9/300
32165/32165 [==============================] - 3s 85us/step - loss: 0.8303 - accuracy: 0.0000e+00
Epoch 10/3

32165/32165 [==============================] - 3s 83us/step - loss: 0.3500 - accuracy: 0.0000e+00
Epoch 75/300
32165/32165 [==============================] - 3s 83us/step - loss: 0.3427 - accuracy: 0.0000e+00
Epoch 76/300
32165/32165 [==============================] - 3s 84us/step - loss: 0.3325 - accuracy: 0.0000e+00
Epoch 77/300
32165/32165 [==============================] - 3s 83us/step - loss: 0.3450 - accuracy: 0.0000e+00
Epoch 78/300
32165/32165 [==============================] - 3s 90us/step - loss: 0.3382 - accuracy: 0.0000e+00
Epoch 79/300
32165/32165 [==============================] - 3s 108us/step - loss: 0.3424 - accuracy: 0.0000e+00
Epoch 80/300
32165/32165 [==============================] - 3s 90us/step - loss: 0.3324 - accuracy: 0.0000e+00
Epoch 81/300
32165/32165 [==============================] - 3s 88us/step - loss: 0.3368 - accuracy: 0.0000e+00
Epoch 82/300
32165/32165 [==============================] - 3s 84us/step - loss: 0.3384 - accuracy: 0.0000e+00
Epoch 83/300


32165/32165 [==============================] - 3s 78us/step - loss: 0.3187 - accuracy: 0.0000e+00
Epoch 148/300
32165/32165 [==============================] - 2s 77us/step - loss: 0.3583 - accuracy: 0.0000e+00
Epoch 149/300
32165/32165 [==============================] - 3s 78us/step - loss: 0.3697 - accuracy: 0.0000e+00
Epoch 150/300
32165/32165 [==============================] - 3s 94us/step - loss: 0.3725 - accuracy: 0.0000e+00
Epoch 151/300
32165/32165 [==============================] - 4s 140us/step - loss: 0.3739 - accuracy: 0.0000e+00
Epoch 152/300
32165/32165 [==============================] - 6s 202us/step - loss: 0.3805 - accuracy: 0.0000e+00
Epoch 153/300
32165/32165 [==============================] - 4s 136us/step - loss: 0.3625 - accuracy: 0.0000e+00
Epoch 154/300
32165/32165 [==============================] - 3s 92us/step - loss: 0.3665 - accuracy: 0.0000e+00
Epoch 155/300
32165/32165 [==============================] - 4s 112us/step - loss: 0.3503 - accuracy: 0.0000e+00
Ep

32165/32165 [==============================] - 3s 96us/step - loss: 0.2943 - accuracy: 0.0000e+00
Epoch 220/300
32165/32165 [==============================] - 3s 94us/step - loss: 0.2985 - accuracy: 0.0000e+00
Epoch 221/300
32165/32165 [==============================] - 3s 101us/step - loss: 0.2962 - accuracy: 0.0000e+00
Epoch 222/300
32165/32165 [==============================] - 3s 108us/step - loss: 0.2953 - accuracy: 0.0000e+00
Epoch 223/300
32165/32165 [==============================] - 3s 85us/step - loss: 0.2968 - accuracy: 0.0000e+00
Epoch 224/300
32165/32165 [==============================] - 2s 73us/step - loss: 0.2971 - accuracy: 0.0000e+00
Epoch 225/300
32165/32165 [==============================] - 2s 76us/step - loss: 0.2896 - accuracy: 0.0000e+00
Epoch 226/300
32165/32165 [==============================] - 3s 87us/step - loss: 0.3070 - accuracy: 0.0000e+00
Epoch 227/300
32165/32165 [==============================] - 2s 74us/step - loss: 0.3098 - accuracy: 0.0000e+00
Epoc

Epoch 292/300
32165/32165 [==============================] - 2s 68us/step - loss: 0.2854 - accuracy: 0.0000e+00 0s - loss: 0.2838 - accuracy: 0.00
Epoch 293/300
32165/32165 [==============================] - 2s 68us/step - loss: 0.2904 - accuracy: 0.0000e+00
Epoch 294/300
32165/32165 [==============================] - 2s 68us/step - loss: 0.2880 - accuracy: 0.0000e+00
Epoch 295/300
32165/32165 [==============================] - 2s 69us/step - loss: 0.2941 - accuracy: 0.0000e+00
Epoch 296/300
32165/32165 [==============================] - 2s 68us/step - loss: 0.2846 - accuracy: 0.0000e+00
Epoch 297/300
32165/32165 [==============================] - 2s 68us/step - loss: 0.2934 - accuracy: 0.0000e+00
Epoch 298/300
32165/32165 [==============================] - 2s 69us/step - loss: 0.2851 - accuracy: 0.0000e+00
Epoch 299/300
32165/32165 [==============================] - 2s 70us/step - loss: 0.2925 - accuracy: 0.0000e+00
Epoch 300/300
32165/32165 [==============================] - 2s 69us/

In [121]:
model_go.predict(train_check[0:10])

array([[4.630949 ],
       [8.738426 ],
       [5.7089767],
       [6.2082515],
       [5.652546 ],
       [6.3284035],
       [7.29165  ],
       [7.37206  ],
       [7.29165  ],
       [7.809046 ]], dtype=float32)

In [124]:
pred3 = model_go.predict(test_check)

In [128]:
submissions3 = pd.DataFrame({'patient_id':test_set['patient_id'],'base_score':pred3})
submissions3.to_csv('submissions4.csv',index = False)

In [127]:
pred3 = pred3.reshape([10760,])

In [138]:
train_check.head()

A    B
0   7   50
1  10   22
2   7    2
3   8   43
4   2  292

In [150]:
test_check.head()

A   B
0  10  22
1   9  35
2   4  13
3   7  21
4   2  44

In [162]:
train_set['review']=pd.qcut(train_set['base_score'],2)

